### ISSUE TITLE
Random Error 6001/6002 when updating/patching 

### ISSUE THREAD

**Issue by Scierix** [ShikyoKira/Project-New-Reign---Nemesis-Main#195]
(https://user-images.githubusercontent.com/63400151/78888894-95e43000-7a30-11ea-8105-f69aa0d855dc.png)

It was working fine before but after I cleaned my game to a vanilla state, after downloading it again and tried to update that's when I get the error

**Comment by ShikyoKira** [comment]
Rerun the operation again. It happens from time to time due to multithreading without proper file lock. It has been addressed in devs build. Thanks for reporting

**Comment by McRex007** [comment]
Had this problem, except it was saying the path was not found. That solution worked, so thank you.

**Comment by Stan555** [comment]
Still not work for me, even I rerun the operation. I clicked the launch button and then it showed up the error 6002; subsequently, when I clicked the button again, the engine closed itself during the processing. 

Checking engine version
Engine is up to date
Version Code: 6553-5036

Initializing behavior generation

Mod Checked 1: nemesis
Mod Checked 2: bcbi
Mod Checked 3: skysa

Mod installed: ImmersiveAnimatedLooting
Mod installed: XPMSE
ERROR(6002): An exception has occured while patching. Report to Nemesis' author immediately
File: None
Message: boost::filesystem::copy_file

Failed to generate behavior

**Comment by xNicklaj** [comment]
Me too

**Comment by Erebus-u** [comment]
I got an 6001 error while trying to update the engine the first time.
said something along the line of unicode string being incorrect (don't remember exactly, this was two days ago)
But I found out that my system locale was the culprit so I changed it to English(United States) and then it worked like a charm.
Just thought I should put it here if someone get the same error.

**Comment by Lethannnn** [comment]
> I got an 6001 error while trying to update the engine the first time.
> said something along the line of "ERROR(6001): An exception has occured while updating. Report to Nemesis' author immediately
> Message: There is no mapping on the target multi-byte code page for the Unicode character."
> 
> But I found out that my system locale was the culprit so I changed it to English(United States) and then it worked like a charm.
> Just thought I should put it here if someone get the same error.

Appreciate it!! I changed language first ,but It didn't work. Then, I realized I should change 'system locale' .
